name: food_waste_reducer
description: A Flutter application to help reduce food waste in Malaysia.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  image_picker: ^1.1.2
  google_generative_ai: ^0.2.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
    - assets/hermit_logo1.png 

