// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSee3gzeBTMJwGTMx4rxQHCX3KwIDVOL8',
    appId: '1:119234190593:web:da187231f7199ea1c7cf00',
    messagingSenderId: '119234190593',
    projectId: 'hermit-355f2',
    authDomain: 'hermit-355f2.firebaseapp.com',
    storageBucket: 'hermit-355f2.firebasestorage.app',
    measurementId: 'G-N5267C64HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzxdsnNeWbHP1WGYhO5BoIHUQH8-AutEg',
    appId: '1:119234190593:android:1de2ea8f734cde3fc7cf00',
    messagingSenderId: '119234190593',
    projectId: 'hermit-355f2',
    storageBucket: 'hermit-355f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFuSR-ip1oxLFd4MngqjN2qFGgET53EwU',
    appId: '1:119234190593:ios:bfc0e5477038f3f4c7cf00',
    messagingSenderId: '119234190593',
    projectId: 'hermit-355f2',
    storageBucket: 'hermit-355f2.firebasestorage.app',
    iosBundleId: 'com.example.hermit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFuSR-ip1oxLFd4MngqjN2qFGgET53EwU',
    appId: '1:119234190593:ios:bfc0e5477038f3f4c7cf00',
    messagingSenderId: '119234190593',
    projectId: 'hermit-355f2',
    storageBucket: 'hermit-355f2.firebasestorage.app',
    iosBundleId: 'com.example.hermit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSee3gzeBTMJwGTMx4rxQHCX3KwIDVOL8',
    appId: '1:119234190593:web:e3c159fb6113ce3cc7cf00',
    messagingSenderId: '119234190593',
    projectId: 'hermit-355f2',
    authDomain: 'hermit-355f2.firebaseapp.com',
    storageBucket: 'hermit-355f2.firebasestorage.app',
    measurementId: 'G-VEHHEVH98E',
  );
}
